title: Vehicle Navigation Enhancement
description: "An online program to find the best and most optimible route for traveling to Qualcomm"
owner_name: Ahaan Vaidyanathan
github_username: Ahaanv19
github_repo: "QAV_Frontend" 
baseurl: "/QAV_Frontend/"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/toolsetup.md
  - navigation/search.md
  - /about
  - navigation/blogs.md
  - README4YML.md